export const enum McLarenMP4Part {
  WheelLeftFront = `WHEEL_LEFT_FRONT`,
  WheelRightFront = `WHEEL_RIGHT_FRONT`,
  WheelLeftFrontHub = `WHEEL_LEFT_FRONT_HUB`,
  WheelRightFrontHub = `WHEEL_RIGHT_FRONT_HUB`,
  WheelLeftFrontParent = `WHEEL_LEFT_FRONT_PARENT`,
  WheelRightFrontParent = `WHEEL_RIGHT_FRONT_PARENT`,
  WheelLeftBack = `WHEEL_LEFT_BACK`,
  WheelRightBack = `WHEEL_RIGHT_BACK`,
  CollisionBody = `COLLISION_BODY`,
  CollisionWheelLeftFront = `COLLISION_WHEEL_FRONT_LEFT`,
  CollisionWheelRightFront = `COLLISION_WHEEL_FRONT_RIGHT`,
  CollisionWheelLeftBack = `COLLISION_WHEEL_BACK_LEFT`,
  CollisionWheelRightBack = `COLLISION_WHEEL_BACK_RIGHT`,
  SennaHead = `HEAD_PARENT`,
  PannelRPM = `PANEL_RPM`,
  PannelGear = `PANEL_GEAR`,
  PannelVelocity = `PANEL_VELOCITY`,
  Steering = `STEERING_WHEEL`,
  GearSwitch = `GEAR_SWITCH`,
  LightBack = `LIGHT_BACK`,
  Body = `SUSPENSION_FRONT`,
  FlagParent = `FLAG_PARENT`,
  MirrorLeft = `MIRROR_LEFT`,
  MirrorRight = `MIRROR_RIGHT`,
}
