export const enum FirstTrackPart {
  Chicanes = `CHICANES`,
  GroundGrass = `GROUND_GRASS`,
  GroundConcrete = `GROUND_CONCRETE`,
  CollisionStartLap = `START_LAP`,
  CollisionFinishLap = `FINISH_LAP`,
  CheckpointParent = `CHECKPOINT_PARENT`,
  ScreenLapTime = `LAP_TIME`,
  ScreenBestLapTime = `BEST_LAP_TIME`,
  TrackLines = `TRACK_LINES`,
  TrackBoxes = `TRACK_BOXES`,
  Track = `TRACK`,
  StartLightsParent = `START_LIGHTS_PARENT`,
  StartLight1 = `START_LIGHT_1`,
  StartLight2 = `START_LIGHT_2`,
  StartLight3 = `START_LIGHT_3`,
  StartLight4 = `START_LIGHT_4`,
  StartLight5 = `START_LIGHT_5`,
  FlagParent = `FLAG_PARENT`,
}